### PR TITLE
Plotting

### LINKED ISSUE #66: 2D live plot should handle 3D data better (not just present the first slice)

### PR DESCRIPTION
**Pull request by plesiopterys**
Closes #66 

The plot generator now returns an updating title and data for a 3D plot with 1D data.
The 2D plot with line data still returns the first xy slice, which is non comprehensive, but nonetheless unchanged.

Indexes start from 1.

This was tested in the demo Jupyter notebook.

### CODE REVIEW

**Comment by plesiopterys** [comment]
Removing "Properties" sections from drivers since it is breaking the docs currently

image

**Comment by plesiopterys** [comment]
image
 
Note: test_voltage was moved to a subfolder, and the __init__.py does not import it.

**Comment by plesiopterys** [comment]
The actual problem stopping docs building is:
image

I suspect docutils may have had a recent update which breaks. I don't think it's our code.

**Comment by plesiopterys** [comment]
Problem Source of docs fail identified:
image

Pull Request #126  is the first pull that the docs started failing. Reason unknown
https://github.com/sandialabs/pyscan/pull/126

**Review by rsbrost — APPROVED** [review]
demo notebook improvements, jasmine's fix to enable sidebar adds and improve docs, keithley2260b syntax important update in doc string, and plotting/plot_generator.py adjustments from jasmine that look intentional and advantageous. Please double check the update to plot_generator.py to make sure before merging. All other file changes fully verified and good to go.

**Comment by plesiopterys** [comment]
Hello!
I am currently out of office on parental leave until August 2024. 

For urgent matters, please text or call me at (310) 307 9272 or cc my contracter email address ***@***.***

Best regards,
Jasmine

**Comment by i-am-mounce** [comment]
Closing this for now. Re open when we can discuss.

**Pull request closed without merging**
