### PR TITLE
List resources feat

### PR DESCRIPTION
**Pull request by rsbrost**
Added new feature to streamline and improve listing and connecting to PyVISA resources.

### CODE REVIEW

**Review by ammounce — CHANGES_REQUESTED** [review]
- this actually not getting the resource, it's printing resource names
- get_resource should return something
- what if the resource is already open or there is already an instance of resource manager?
- should we automatically close the resource
- functionality might need to be separated between listing resources and opening a single target resource
- Does opening resource manager several times cause errors?
- Should this be a method of a class 'DeviceManager?'

**Comment by rsbrost** [comment]
- There is no problem creating multiple instances of resource manager or opening it as many times as we want. 
- There is no problem if resources are already connected...
- so technically we don't need to automatically close the resource when getting resources, but it is best practices to only connect to the instruments you want to so the others remain available for connection elsewhere.
- I like the idea of a DeviceManager class where we could include lots of useful device specific functionalities and think this will be a helpful structure for future growth.

**Comment by rsbrost** [comment]
Now get_resources() functions like this:
image

**Comment by rsbrost** [comment]
This pull request now accounts for Andy's requested changes for keeping this pull request simple for the time being (see the above implementation); however, I am pushing my alternative iteration implementing a DeviceManager class to a separate branch since it is still unclear if we will want this eventually and now we will have it for later in case we decide to choose that method instead down the road.

The DeviceManager class has the advantage of having an automatically populated resource_manager and resources_listed attribute; however, the disadvantage that these methods cannot be called to list resources independently without first creating an instance of the class.

**Review by i-am-mounce — CHANGES_REQUESTED** [review]
if resource is initially open, keep open
list_resources, change to print
return as key-value pairs

**Comment by rsbrost** [comment]
- Updated get_resources.py to keep instruments open rather than close them, as otherwise this could close instruments that were open before and there is no way to tell if an instrument was open before via the pyvisa resource manager. 
- The list_resources function parameter was changed to print_resources (since print was not a valid variable for booleans since it is interpreted as the native function first and foremost).
- Updated the return to return a resource_dict of key value pairs, linking connection addresses to their queried IDs when available, now including a note that the ID couldn't be queried when unavailable.

**Review by i-am-mounce — APPROVED** [review]

**Pull request merged**
