### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by i-am-mounce**
What do you think?

### CODE REVIEW

**Comment by plesiopterys** [comment]
Suggestions:

- edit same thing on index.md in docs
- Correct the grammar:
Original: "If Pyscan contributes to a project that leads to publication, please let us know and acknowledging pyscan use as:"
Suggested: "If Pyscan contributes to a project that leads to publication, please acknowledge this using:"

**Comment by plesiopterys** [comment]
Do not publish names until you get permission for contributors
Move Contributors section to Wiki and include a link on the README/index

**Comment by plesiopterys** [comment]
Can we use this wording
A U.S. Department of Energy Nanoscale Science User Facility

ask Ryan Wixom???

**Comment by plesiopterys** [comment]
If Pyscan contributes to a project that leads to publication, please **let us know and** acknowledge this using:

**Comment by rsbrost** [comment]
approved.

**Review by rsbrost — APPROVED** [review]
Looks good.

**Pull request merged**
