### PR TITLE
Drivers

### PR DESCRIPTION
**Pull request by plesiopterys**
added functionality for dict_drivers in instrument driver.py

tested it on agilent33500 driver, but did not keep changes to that driver since it was unnecessary.
functionality can be used with other drivers now.

Return value when querying a dict_value property looks like:
{1: 'ON'}

and the 'return_type' of the property must specify which type is used for keys in the dictionary. For the example above, the 'return_type' must be int.

If 'return_type' is str, then dictionary must be matching as follows:
{'1': 'ON'}

### CODE REVIEW

**Comment by plesiopterys** [comment]
I am up to date with main, but why am I getting failing checks for :

6     W291 trailing whitespace
1     W293 blank line contains whitespace

**Review by rsbrost — CHANGES_REQUESTED** [review]
minor flake8 errors causing the build to fail. Please fix these first and then I'll take a look at approving this pull request, though I may need to have you walk me through the changes or revert to Andy's judgment since my current understanding of pyscan drivers is minimal.

**Comment by plesiopterys** [comment]
I was under the impression that we were overriding the trailing whitespaces error - am I supposed to fix all of those in the doc strings or is there something in the flake8 file that I haven't done right and so I'm still getting those errors?

**Comment by plesiopterys** [comment]
I just fixed the flake8 errors

**Comment by i-am-mounce** [comment]
There's a rebasing issue can you check that drivers is up to date with main?

**Review by rsbrost — APPROVED** [review]
Your changes look mostly good to me; however, it seems it might make more sense to use an assert statement when the set_dict_values_property fails so that it will do more than just print a value error and will actually break instead. This may not be what you want though so the code looks good if you simply want it to let the user know that their new dict value wasn't added while ensuring the program keeps running as it otherwise would. I approve this as long as this is in fact intentional taking into account my inquiry.

Since I am not entirely sure what the new function is supposed to do, I recommend seeking Andy's feedback before pulling depending on your confidence level.

**Comment by plesiopterys** [comment]
Sounds good, Andy just dropped by and was working on custom errors for this so that there can be an actual error instead of the current string return value.
We can just wait till Andy takes a look and approves the changes then

**Pull request merged**
