### PR TITLE
fix(core): update load_experiment so that the runinfo.measured attribute has a list of the actual measured datasets

### LINKED ISSUE #189: hdf5 files do not save runinfo.measured
runinfo.measured is important for existing plot commands like PlotGenerator().  When you use the expt created in a jupyter notebook, the measured list is present.  If you use ps.load_experiment(), measured is an empty list.

In checking on this problem,
1. save_metadata() runs recursive_to_dict() and json.dumps()
2. recursive_to_dict() makes a dictionary with measured and the list is correct at this point
3. directly checking the hdf5 file runinfo attr: f.attrs['runinfo'], measured is an empty list.

### PR DESCRIPTION
**Pull request by mplilly4395**
Updated load_experiment.py to read datasets in the hdf5 file (which included measured data and generated data from scan0, ...) and load only the measured data in runinfo.measured.

tests were updated so this change to load_experiment did not lead to failed tests

closes #189

### CODE REVIEW

**Review by i-am-mounce — CHANGES_REQUESTED** [review]
For future proofing, maybe use a while loop as
> while hasattr(runinfo, 'scan{i}'

Can we call 'generated_datasets' 'find_measured_datasets'?

Change generated to 'measured' to keep naming conventions he same.

**Review by rsbrost — COMMENTED** [review]
I approve the changes to tests.

**Comment by mplilly4395** [comment]
I changed the function to find_measured_datasets.  For the lists of datasets, all_datasets are the names of all of the datasets in the hdf5 file.  These datasets are either datapoints measured in the measure_function (e.g. v1_readout) or they are datasets generated by the Experiment (e.g. v1_voltage, repeat, ...).  I am using the local variable "generated" to keep track of this second list.

**Review by rsbrost — APPROVED** [review]
Andy's feedback has been factored into this pull by Mike. Furthermore, I approve these changes. Please note, we may need to test this with more types of scans than are included in the demo notebook; however, it is passing test cases with all scan types from the demo nbs.

**Review by i-am-mounce — APPROVED** [review]

**Pull request merged**
